kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: akri-fleet
  namespace: fleet-default
spec:
  repo: https://github.com/ranchergovernment-sandbox/akri-fleet.git
  branch: main
  targets:
  - name: akri
    clusterSelector:
      matchLabels:
        akri: enabled
  paths:
  - ./akri
  - ./akri-devices